project:
  type: website
  output-dir: docs

format:
  html:
    theme: litera
  
website: 
  title: "Interactive Exploration of Multi-Omic Medical Research"
  description: A website built with Quarto to analyze the transcription and epigenetics data
  navbar:
    logo: image/logo5.png # shows in the top-left navbar
    title: MedOmics Hub
    right:
      - text: Home
        href: index.qmd
      - text: Blog
        href: blog/index.qmd 
      - text: shiny
        href: shiny/shiny.qmd 
      - text: Events
        href: events/events.qmd
      - text: About
        href: about/index.qmd
  page-footer:
    left: "© 2025 MedOmics Hub"
    right: 'Made with [Quarto](https://quarto.org)'
    

    
